- hosts: namenode
  tasks:
    - include_vars: var.yml    
    - name: install jdk
      yum:
        name: "{{jdk_loc}}"
        state: present
    - lineinfile:
        path: /root/.bashrc
        line: "export JAVA_HOME=/usr/java/jdk1.8.0_171-amd64/\nexport PATH=/usr/java/jdk1.8.0_171-amd64/bin/:$PATH"
    - command: "rpm -ivh {{hadoop_loc}} --force"
- hosts: namenode
  tasks:
      - include_vars: var.yml
      - name: "seting up namenode"
        file:
           path: /nn
           state: directory
      - template:
             src: /var/www/cgi-bin/project/config/core-site.xml.j2
             dest: /etc/hadoop/core-site.xml
      - template:
             src: /var/www/cgi-bin/project/config/hdfs-site.xml.j2
             dest: /etc/hadoop/hdfs-site.xml
      - command: "hadoop namenode -format -force"
      - command: "hadoop-daemon.sh start namenode"
      - iptables:
          flush: true
