- hosts: tasknode
  tasks:
    - include_vars: var.yml  
    - name: install jdk
      yum:
        name: "{{jdk_loc}}"
        state: present
    - lineinfile:
        path: /root/.bashrc
        line: "export JAVA_HOME=/usr/java/jdk1.8.0_171-amd64/\nexport PATH=/usr/java/jdk1.8.0_171-amd64/bin/:$PATH"
    - command: "rpm -ivh {{hadoop_loc}} --force"
              
- hosts: tasknode
  tasks:
      - include_vars: var.yml
      - name: "seting up datanode"
        template:
             src: /var/www/cgi-bin/project/mapred-site.xml.j2
             dest: /etc/hadoop/mapred-site.xml
      - command: "hadoop-daemon.sh start tasktracker"

